version: "2.1"
orbs:
  node: circleci/node@5.0.3
jobs:
  integration-test:
    machine:
      image: ubuntu-2204:2022.10.1
    steps:
      - checkout
      - restore_cache:
          key: v1-deps
      - node/install:
          node-version: "16.15.1"
      - run:
          name: Get environment configuration
          command: echo $TEST_CONFIG_ENV_JSON > config.test.json
      - run:
          name: Install PM2
          command: npm i -g pm2
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-deps
          paths:
            - node_modules
      - run:
          name: Prepare environment
          command: npm run test:prepare
      - run:
          name: Run tests
          command: npm test || true
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
      - run:
          name: Send notification with test results to Slack
          command: node tests-summary.js
      - store_test_results:
          path: ./reports/
workflows:
  test_magmooty_api:
    jobs:
      - integration-test:
          context: integration_tests_slack_notifications
