version: "2.1"
orbs:
  node: circleci/node@5.0.3
jobs:
  integration-test:
    machine:
      image: ubuntu-2204:2022.10.1
    steps:
      - checkout
      - node/install:
          node-version: "16.15.1"
      - run: 
          command: echo $TEST_CONFIG_ENV_JSON > config.test.json
          name: Get environment configuration
      - run: 
          command: npm i -g pm2
          name: Install PM2
      - run: 
          command: npm install
          name: Install dependencies
      - run: 
          command: npm run test:prepare
          name: Prepare environment
      - run: 
          command: npm test
          name: Run tests
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
      - store_test_results:
          path: ./reports/
workflows:
  test_magmooty_api:
    jobs:
      - integration-test
