version: "3.3"
services:
  app:
    container_name: app
    build: 
      context: "../.."
      args:
        SELECTED_CONFIG: dev
    ports:
      - "7200:7200"
  redis:
    container_name: redis
    image: redis
    command: redis-server --save 60 1
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"
  zookeeper:
    container_name: "zookeeper"
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: "kafka"
    image: docker.io/bitnami/kafka:3.2
    hostname: localhost
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  es:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: es01
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - node.name=local-magmooty
      - cluster.name=es-magmooty-local-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  esdata:
    driver: local
  redis_data:
    driver: local
  dynamodb_data:
    driver: local
